x-common: &common
  networks:
    - person-network
  restart: unless-stopped
  logging:
    options:
      max-size: 50m
      max-file: "3"

services:
  api:
    !!merge <<: *common
    build: .
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/persondb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  postgres:
    !!merge <<: *common
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=persondb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  person-network:
    name: person-network
    driver: bridge

volumes:
  postgres-data:
