{
 "title": "Spring Boot Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(application)" } },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$app_name\", uri=~\"/api.*\", uri!~\"/api-docs.*\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri, method) (http_server_requests_seconds_count{application=\"$app_name\", uri=~\"/api.*\", uri!~\"/api-docs.*\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri, method)(http_server_requests_seconds_sum{application=\"$app_name\", uri=~\"/api.*\", uri!~\"/api-docs.*\"}) / sum by(uri, method)(http_server_requests_seconds_count{application=\"$app_name\", uri=~\"/api.*\", uri!~\"/api-docs.*\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$app_name\", outcome=\"SERVER_ERROR\", uri=~\"/api.*\", uri!~\"/api-docs.*\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri, method) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"2.*\", uri=~\"/api.*\", uri!~\"/api-docs.*\"}) / sum by(uri, method) (http_server_requests_seconds_count{application=\"$app_name\", uri=~\"/api.*\", uri!~\"/api-docs.*\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri, method) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"4.*\", uri=~\"/api.*\", uri!~\"/api-docs.*\"}) / sum by(uri, method) (http_server_requests_seconds_count{application=\"$app_name\", uri=~\"/api.*\", uri!~\"/api-docs.*\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri, method) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"5.*\", uri=~\"/api.*\", uri!~\"/api-docs.*\"}) / sum by(uri, method) (http_server_requests_seconds_count{application=\"$app_name\", uri=~\"/api.*\", uri!~\"/api-docs.*\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_requests_seconds_bucket{application=\"$app_name\", uri=~\"/api.*\", uri!~\"/api-docs.*\"}[1m])) by(uri, method, le))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{application=\"$app_name\", uri=~\"/api.*\", uri!~\"/api-docs.*\"}[1m])) by(uri, method, le))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri, method)(rate(http_server_requests_seconds_count{application=\"$app_name\", uri=~\"/api.*\", uri!~\"/api-docs.*\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Log of All Spring Boot Apps",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"fluent-bit\"} \n| pattern `<date> <time> [<thread>] [<trace_id>] [<span_id>] <level> <logger> - <msg>` \n| line_format \"{{.job}}\\t{{.level}}\\ttrace_id={{.trace_id}}\\tspan_id={{.span_id}}\\t{{.msg}}\""
    }
   ]
  }
 ]
}